server test by existing api format
ainize-team/TTI-FastAPI pull request #2
Opened 2022-08-17 07:10 UTC by jikerbug

기존 request 형식에 맞게 요청을 보내고 응답을 받는 test server code 입니다

2022-08-17 07:26 UTC, 589hero commented on main.py
> +async def run_tti_model(prompt, steps, width, height, images_num, diversity_scale):
실제 Text To Image 모델을 로드해서 이미지를 생성하도록 작성해주실 수 있나요?

2022-08-17 07:28 UTC, 589hero commented on start.sh
> +uvicorn main:app --host 0.0.0.0 --port 8000 --reload
지금 shell파일은 삭제해도 될 것 같고, Dockerfile를 작성해서 Dockerfile 컨테이너 상에서 서버가 실행될 수 있도록 바꿔주실 수 있나요?

2022-08-17 07:31 UTC, jikerbug commented on main.py
> +async def run_tti_model(prompt, steps, width, height, images_num, diversity_scale):
feature 나눠서 하려 하는데, 한번에 하는 게 좋을 까요?

2022-08-17 07:32 UTC, jikerbug commented on start.sh
> +uvicorn main:app --host 0.0.0.0 --port 8000 --reload
아 그러면 전체적으로 다 구현하겠습니다

2022-08-17 07:35 UTC, jikerbug commented
모델 연동 & 도커라이징 완료후 재 커밋하겠습니다

2022-08-17 07:40 UTC, 589hero commented on main.py
> +async def run_tti_model(prompt, steps, width, height, images_num, diversity_scale):
네 한 번에 하는게 좋을 듯 합니다.

2022-08-17 09:08 UTC, godhw commented on main.py
> +async def generate(request: Request):
async로 구현된 이유가 있을까요??

2022-08-17 09:08 UTC, godhw commented on main.py
> +    print(request_data[5])
[logging library](https://github.com/Delgan/loguru)를 사용해보는 건 어떨까요?

2022-08-17 09:08 UTC, godhw commented on main.py
> +async def generate(request: Request):
return type annotation도 하는 것은 어떨까요? [어노테이션 예시](https://wikidocs.net/134883)

2022-08-17 09:58 UTC, byeongal requested changes

2022-08-17 09:58 UTC, byeongal commented on app.py
> +# @title Import stuff
필요없는 파일 제거 부탁 드리겠습니다.

2022-08-17 15:15 UTC, jikerbug commented on main.py
> +async def generate(request: Request):
queue가 아닌 async로 한 이유는 현재 코드가 모델 서빙 용이 아니라 테스트 용이라서 최대한 간단하게 만들기 위함입니다.

이에 대한 질문이 맞나요? 아니라면

함수 내에서 호출하는 
base64_data = await make_images(data)
의 경우 현재는 async function 처럼 작동하지는 않지만 이미지 생성 모델을 연동할 경우는 await을 적용해야 해서 async로 하였습니다.

로 추가 코멘트 하겠습니다

2022-08-17 15:16 UTC, jikerbug commented on main.py
> +async def generate(request: Request):
annotation 반영하겠습니다. 감사합니다!

2022-08-18 01:52 UTC, jikerbug commented on app.py
> +# @title Import stuff
넵

2022-08-18 09:14 UTC, jikerbug commented
커밋을 잘못 보냈네요, 아직 구현 중입니다!

2022-08-18 16:12 UTC, jujeongho0 approved these changes

2022-08-19 03:36 UTC, jikerbug commented on main.py
> +    print(request_data[5])
참고해보겠습니다!

2022-08-19 06:49 UTC, closed without merging